Repository loudsmilestudios/TetraForce, pull requests merged in 2021-06, with the labels that each got.

#252 Update README
  README.md
Labels: documentation

#265 Fade out music when changing maps
  engine/global.gd
  sound/sound.gd
Labels: audio

#272 Added clarifying question to PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#270 Add ESC Menu & GameOver Menu Fixes
  effects/screenfx.tscn
  engine/main.gd
  engine/main.tscn
  engine/network.gd
  entities/player/player.gd
  project.godot
  ui/esc_menu/esc_menu.gd
  ui/esc_menu/esc_menu.tscn
  ui/hud/hud.gd
  ui/layovers/gameover.gd
  ui/layovers/gameover.tscn
Labels: bug, enhancement

#276 Various Options Improvements
  engine/keybinds.gd
  engine/main.gd
  engine/main.tscn
  ui/esc_menu/esc_menu.gd
  ui/esc_menu/esc_menu.tscn
  ui/main/characterselect.gd
  ui/options/gameplay.gd
  ui/options/gameplay.tscn
  ui/options/keybinds.tscn
  ui/options/options.gd
  ui/options/options.tscn
  ui/options/options_panel.gd
  ui/options/options_panel.tscn
  ui/options/save.gd
  ui/options/save.tscn
  ui/options/sound.gd
  ui/options/sound.tscn
  ui/theme/scrollbar.png
  ui/theme/slider_area.png
  ui/theme/slider_area.png.import
  ui/theme/slider_button.png
  ui/theme/slider_button.png.import
  ui/theme/theme.tres
Labels: enhancement
